#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Author:fangshuai
# date:2020/xx/xx
######-----------随机抽样方案
qg_sql1=""""
SELECT
  CASE
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 15 THEN '0-15分钟'
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) > 15  AND TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 30 THEN '15-30分钟'
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) > 30  AND TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 60 THEN '30-60分钟'
    ELSE '60分钟'
  END SMXHSJ,
  COUNT(1) total
FROM FX_SM_JL t
WHERE t.YXBZ = 'Y'
  AND t.CLZT = '5'
  AND t.KSSJ > CONCAT(DATE(DATE_ADD(NOW(),INTERVAL -1 DAY)), ' 16:00:00')
  AND t.KSSJ <= CONCAT(DATE(NOW()), ' 16:00:00')
  AND EXISTS(SELECT 1 FROM FX_SJCYFA t1 WHERE t1.SJCYFAXH = t.YWWYM AND t1.FXZT_DM = '0001' AND t1.YXBZ = 'Y')
GROUP BY SMXHSJ;"""
qg_sql2="""
SELECT COUNT(1) total
  FROM FX_SJCYFA t
 WHERE t.FXZT_DM = '0001'
   AND t.YSJCYFAXH IS NULL
   AND t.LRRQ <= CONCAT(DATE(NOW()), ' 16:00:00');"""
qg_sql3="""SELECT COUNT(1) total
  FROM FX_SJCYFA t
 WHERE t.FXZT_DM = '0001'
   AND t.YXBZ = 'Y'
   AND t.LRRQ <= CONCAT(DATE(NOW()), ' 16:00:00');"""
#######全面风险方案
qg_sql4="""SELECT
  CASE
    WHEN FXFAZT = '0' THEN '待发布'
    WHEN FXFAZT = '1' THEN '已发布'
    WHEN FXFAZT = '2' THEN '已禁用'
    WHEN FXFAZT = '3' THEN '预发布'
    ELSE '未知状态'
  END 风险方案状态,
  COUNT(1) total
FROM
  FX_QMFXFA t
WHERE t.FXZT_DM = '0001'
  AND t.YXBZ = 'Y'
  AND t.LRRQ > CONCAT(DATE(DATE_ADD(NOW(),INTERVAL -1 DAY)), ' 16:00:00')
  AND t.LRRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
GROUP BY FXFAZT;"""
qg_sql5="""SELECT
  CASE
    WHEN FXFAZT = '0' THEN '待发布'
    WHEN FXFAZT = '1' THEN '已发布'
    WHEN FXFAZT = '2' THEN '已禁用'
    WHEN FXFAZT = '3' THEN '预发布'
    ELSE '未知状态'
  END 风险方案状态,
  COUNT(1) total
FROM
  FX_QMFXFA t
WHERE t.FXZT_DM = '0001'
  AND t.YXBZ = 'Y'
  AND t.LRRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
GROUP BY FXFAZT;
"""
qg_sql6="""
SELECT COUNT(1) total
FROM FX_QMFXFA t1
WHERE t1.FXZT_DM = '0001'
  AND t1.YXBZ = 'Y'
  AND t1.LRRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
  AND EXISTS (SELECT 1 FROM FX_QMFASM_PZ t WHERE t.FXFAXH = t1.FXFAXH AND t.FXFASMPL <> '06' AND t.YXBZ = 'Y');"""
qg_sql7="""SELECT COUNT(1) total
FROM FX_QMFXFA t1
WHERE t1.FXZT_DM = '0001'
  AND t1.YXBZ = 'Y'
  AND t1.LRRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
  AND EXISTS (SELECT 1 FROM FX_QMFASM_PZ t WHERE t.FXFAXH = t1.FXFAXH AND t.GXPL <> '05' AND t.YXBZ = 'Y');"""
qg_sql8="""
SELECT COUNT(1) total
  FROM FX_QMFXFA t1
 WHERE t1.FXZT_DM = '0001'
   AND t1.YXBZ = 'Y'
   AND t1.LRRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
   AND EXISTS(SELECT 1 FROM FX_QMFASM_PZ t WHERE t.FXFAXH = t1.FXFAXH AND t.GXYXQZ <> '2021-08-31' AND t.YXBZ = 'Y');"""
qg_sql9="""SELECT COUNT(1) total
  FROM FX_QMFXFA t1
 WHERE t1.FXZT_DM = '0001'
   AND t1.YXBZ = 'Y'
   AND t1.LRRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
   AND t1.FXFAZT = '1'
   AND EXISTS(SELECT 1 FROM FX_QMFAMX_GX t WHERE t.FXFAXH = t1.FXFAXH AND t.FXMXDM IN('MX000000000000000106','MX144010000000504149') AND t.YXBZ = 'Y');"""
#######方案扫描监控
qg_sql10="""SELECT
  CASE
    WHEN t.CLZT = '0' THEN '待处理'
    WHEN t.CLZT = '1' THEN '处理中'
    WHEN t.CLZT = '2' THEN '调用成功'
    WHEN t.CLZT = '3' THEN '调用失败'
    WHEN t.CLZT = '4' THEN '禁用'
    WHEN t.CLZT = '5' THEN '处理成功'
    WHEN t.CLZT = '6' THEN '处理失败'
    ELSE '未知状态'
  END 处理状态,
  COUNT(1) total
FROM
  FX_SM_JL t
WHERE t.YXBZ = 'Y'
  AND t.KSSJ > CONCAT(DATE(DATE_ADD(NOW(),INTERVAL -1 DAY)), ' 16:00:00')
  AND t.KSSJ <= CONCAT(DATE(NOW()), ' 16:00:00')
  AND EXISTS(SELECT 1 FROM FX_SJCYFA t1 WHERE t1.SJCYFAXH = t.YWWYM AND t1.FXZT_DM = '0001' AND t1.YXBZ = 'Y')
GROUP BY CLZT;"""
qg_sql11="""SELECT
  CASE
    WHEN t.YWLX_DM = '03' THEN '新增扫描'
    ELSE '更新扫描'
  END 扫描类型,
  CASE
    WHEN t.CLZT = '0' THEN '待处理'
    WHEN t.CLZT = '1' THEN '处理中'
    WHEN t.CLZT = '2' THEN '调用成功'
    WHEN t.CLZT = '3' THEN '调用失败'
    WHEN t.CLZT = '4' THEN '禁用'
    WHEN t.CLZT = '5' THEN '处理成功'
    WHEN t.CLZT = '6' THEN '处理失败'
    ELSE '未知状态'
  END 处理状态,
  COUNT(1) total
FROM
  FX_SM_JL t
WHERE t.YXBZ = 'Y'
  AND t.KSSJ > CONCAT(DATE(DATE_ADD(NOW(),INTERVAL -1 DAY)), ' 16:00:00')
  AND t.KSSJ <= CONCAT(DATE(NOW()), ' 16:00:00')
  AND t.YWLX_DM IN('03','05')
  AND EXISTS(SELECT 1 FROM FX_QMFXFA t1 WHERE t1.FXFAXH = t.YWWYM AND t1.FXZT_DM = '0001' AND t1.YXBZ = 'Y')
GROUP BY YWLX_DM,CLZT;"""
qg_sql12="""SELECT COUNT(1) total
  FROM FX_SJCYFA t
 WHERE t.FXZT_DM = '0001'
   AND t.SJCYFAZT = '1'
   AND t.YXBZ = 'Y'
   AND EXISTS(SELECT 1 FROM FX_SM_JL t1 WHERE t1.YWWYM = t.SJCYFAXH AND NOW() > DATE_ADD(t1.EXECUTE_TIME,INTERVAL 6 HOUR))
   AND NOT EXISTS(SELECT 1 FROM FX_SM_JL t1 WHERE t1.YWWYM = t.SJCYFAXH AND t1.CLZT = '5');"""
qg_sql13="""SELECT COUNT(1) total FROM(
SELECT t3.FXFAXH FROM (
SELECT t.FXFAXH
FROM FX_QMFXFA t
WHERE t.FXZT_DM = '0001'
   AND t.FXFAZT = '1'
   AND t.YXBZ = 'Y'
   AND NOT EXISTS(SELECT 1 FROM FX_SM_JL t1 WHERE t1.YWWYM = t.FXFAXH AND t1.CLZT = '5')
) t3 WHERE EXISTS(SELECT 1 FROM FX_QMFAMX_GX t1 WHERE t1.FXFAXH = t3.FXFAXH AND t1.YXBZ = 'Y' AND t1.FXMXDM = 'MX144010000000504149'
   AND EXISTS(SELECT 1 FROM FX_SM_JL t2 WHERE t2.YWWYM = t1.FXFAXH AND NOW() > DATE_ADD(t2.EXECUTE_TIME,INTERVAL 6 HOUR))) 
UNION ALL 
SELECT t3.FXFAXH FROM (
SELECT t.FXFAXH
FROM FX_QMFXFA t
WHERE t.FXZT_DM = '0001'
   AND t.FXFAZT = '1'
   AND t.YXBZ = 'Y'
   AND NOT EXISTS(SELECT 1 FROM FX_SM_JL t1 WHERE t1.YWWYM = t.FXFAXH AND t1.CLZT = '5')
) t3 WHERE EXISTS(SELECT 1 FROM FX_QMFAMX_GX t1 WHERE t1.FXFAXH = t3.FXFAXH AND t1.YXBZ = 'Y' AND t1.FXMXDM = 'MX000000000000000106'
   AND EXISTS(SELECT 1 FROM FX_BCHY_WCB t2 WHERE t2.FXFAXH = t1.FXFAXH AND t2.YWLX_DM = 'FX000001005' 
   AND t2.CLZT = '2' AND NOW() > DATE_ADD(t2.XGRQ,INTERVAL 6 HOUR)))  
  ) t4;"""
qg_sql14="""SELECT
  CASE
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 15 THEN '0-15分钟'
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) > 15  AND TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 30 THEN '15-30分钟'
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) > 30  AND TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 60 THEN '30-60分钟'
    ELSE '60分钟'
  END SMXHSJ,
  COUNT(1) total
FROM FX_SM_JL t
WHERE t.YXBZ = 'Y'
  AND t.YWLX_DM = '03'
  AND t.CLZT = '5'
  AND t.KSSJ > CONCAT(DATE(DATE_ADD(NOW(),INTERVAL -1 DAY)), ' 16:00:00')
  AND t.KSSJ <= CONCAT(DATE(NOW()), ' 16:00:00')
  AND EXISTS(SELECT 1 FROM FX_QMFXFA t1 WHERE t1.FXFAXH = t.YWWYM AND t1.FXZT_DM = '0001' AND t1.YXBZ = 'Y')
GROUP BY SMXHSJ;"""
qg_sql15="""SELECT
  CASE
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 15 THEN '0-15分钟'
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) > 15  AND TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 30 THEN '15-30分钟'
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) > 30  AND TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 60 THEN '30-60分钟'
    ELSE '60分钟'
  END SMXHSJ,
  COUNT(1) total
FROM FX_SM_JL t
WHERE t.YXBZ = 'Y'
  AND t.YWLX_DM = '05'
  AND t.CLZT = '5'
  AND t.KSSJ > CONCAT(DATE(DATE_ADD(NOW(),INTERVAL -1 DAY)), ' 16:00:00')
  AND t.KSSJ <= CONCAT(DATE(NOW()), ' 16:00:00')
  AND EXISTS(SELECT 1 FROM FX_QMFXFA t1 WHERE t1.FXFAXH = t.YWWYM AND t1.FXZT_DM = '0001' AND t1.YXBZ = 'Y')
GROUP BY SMXHSJ;"""
qg_sql16="""SELECT
  CASE
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 15 THEN '0-15分钟'
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) > 15  AND TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 30 THEN '15-30分钟'
    WHEN TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) > 30  AND TIMESTAMPDIFF(MINUTE,t.KSSJ, t.JSSJ) <= 60 THEN '30-60分钟'
    ELSE '60分钟'
  END SMXHSJ,
  COUNT(1) total
FROM FX_SM_JL t
WHERE t.YXBZ = 'Y'
  AND t.CLZT = '5'
  AND t.KSSJ > CONCAT(DATE(DATE_ADD(NOW(),INTERVAL -1 DAY)), ' 16:00:00')
  AND t.KSSJ <= CONCAT(DATE(NOW()), ' 16:00:00')
  AND EXISTS(SELECT 1 FROM FX_SJCYFA t1 WHERE t1.SJCYFAXH = t.YWWYM AND t1.FXZT_DM = '0001' AND t1.YXBZ = 'Y')
GROUP BY SMXHSJ;"""
#######总对总核验
qg_sql17="""SELECT COUNT(DISTINCT swjg_dm) 省份数量
FROM (
         SELECT CONCAT(SUBSTR(SJGSDQ, 1, 3), '00') swjg_dm
         FROM fx_fxhy_zb
         WHERE YXBZ = 'Y'
           AND FQHYRQ IS NOT NULL
           AND XGRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
           AND SUBSTR(SJGSDQ, 1, 5) NOT IN ('14403', '13502', '13302', '12102', '13702')
         UNION ALL
         SELECT SUBSTR(SJGSDQ, 1, 5) swjg_dm
         FROM fx_fxhy_zb
         WHERE YXBZ = 'Y'
           AND FQHYRQ IS NOT NULL
           AND XGRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
           AND SUBSTR(SJGSDQ, 1, 5) IN ('14403', '13502', '13302', '12102', '13702')
     ) t;"""
qg_sql18="""SELECT 
 COUNT(DISTINCT CASE WHEN jd.xhyrysl=jd.ywchyrysl THEN sf END) AS 已完成总对总核验省份数量,
 COUNT(DISTINCT CASE WHEN jd.xhyrysl>jd.ywchyrysl AND ts<=7 THEN sf END) AS 7天内未完成总对总核验省份数量,
 COUNT(DISTINCT CASE WHEN jd.xhyrysl>jd.ywchyrysl AND ts>7 AND ts<=14 THEN sf END) AS 7至14天内未完成总对总核验省份数量,
 COUNT(DISTINCT CASE WHEN jd.xhyrysl>jd.ywchyrysl AND ts>14 THEN sf END) AS 超过14天内未完成总对总核验省份数量 
FROM f_rt_fxgl_zdzhy_jdtj_cxtj jd
JOIN (SELECT zb.*,DATEDIFF(NOW(),zb.fqhyrq) AS ts,
      CASE WHEN SUBSTR(zb.slswjg_dm, 1, 5) IN ('14403', '13502', '13302', '12102', '13702') THEN SUBSTR(zb.slswjg_dm, 1, 5) 
      ELSE SUBSTR(zb.slswjg_dm, 1, 3) END AS sf FROM dim_fx_fxhy_zb zb WHERE zb.yxbz='Y' AND zb.fqhyrq IS NOT NULL) zb 
ON jd.sjcyfaxh=CAST(zb.fxfaxh AS VARCHAR) 
WHERE jd.yxbz='Y';"""
#######补充核验
qg_sql9="""SELECT
  COUNT(DISTINCT swjg_dm) 已发起省份数量
FROM
  (SELECT CONCAT(SUBSTR(SJGSDQ, 1, 3), '00') swjg_dm
  FROM
    fx_fxhy_zb
  WHERE YXBZ = 'Y'
    AND BCHYFQZT = '1'
    AND XGRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
    AND SUBSTR(SJGSDQ, 1, 5) NOT IN ('14403','13502','13302','12102','13702')
  UNION ALL
  SELECT SUBSTR(SJGSDQ, 1, 5) swjg_dm
  FROM
    fx_fxhy_zb
  WHERE YXBZ = 'Y'
    AND BCHYFQZT = '1'
    AND XGRQ <= CONCAT(DATE(NOW()), ' 16:00:00')
    AND SUBSTR(SJGSDQ, 1, 5) IN ('14403','13502','13302','12102','13702')) t;
"""
qg_sql20="""SELECT
    t4.TJQJ 统计区间,
    COUNT(DISTINCT t4.SWJG_DM) 省份数量 
FROM (
  SELECT
    t3.SWJG_DM,
    (
      CASE
        WHEN t3.WCXH IS NOT NULL THEN '已完成补充核验'
        WHEN t3.WCXH IS NULL AND t3.DQQJ <= 10 THEN '10天内未完成'
        WHEN t3.WCXH IS NULL AND t3.DQQJ > 10 AND t3.DQQJ <= 20 THEN '10-20天未完成'
        WHEN t3.WCXH IS NULL AND t3.DQQJ > 20 AND t3.DQQJ <= 30 THEN '20-30天未完成'
        WHEN t3.WCXH IS NULL AND t3.DQQJ > 30 THEN '30天以上未完成'
      END
    ) TJQJ,
    t3.FXFAXH
  FROM
    (SELECT (
        CASE
          WHEN SUBSTR(t1.SJGSDQ, 1, 5) IN ('14403','13502','13302','12102','13702') THEN SUBSTR(t1.SJGSDQ, 1, 5)
          ELSE CONCAT(SUBSTR(t1.SJGSDQ, 1, 3), '00')
        END
      ) SWJG_DM,
      t1.FXFAXH,
      t2.WCXH,
      TIMESTAMPDIFF(DAY, t1.lrrq, CONCAT(DATE(NOW()),' 16:00:00')) DQQJ
    FROM
      fx_fxhy_zb t1
      LEFT JOIN (SELECT WCXH, FXFAXH FROM fx_bchy_wcb WHERE YWLX_DM = 'FX000001005' AND YXBZ = 'Y') t2 ON t1.FXFAXH = t2.FXFAXH
    WHERE t1.YXBZ = 'Y'
      AND t1.BCHYFQZT = '1') t3
) t4 
GROUP BY t4.TJQJ;"""
#######人工复评
qg_sql21="""SELECT
   COUNT(DISTINCT t.SJ_SWJG_DM) 已发起省份数量
FROM
  FX_FPRW_TSJLB t 
WHERE t.YXBZ = 'Y'
  AND EXISTS(SELECT 1 FROM FX_QMFAMX_GX t1 WHERE t1.FXFAXH = t.FXFAXH AND t1.YXBZ = 'Y' AND t1.FXMXDM = 'MX000000000000000106');"""
qg_sql22="""SELECT
   COUNT(DISTINCT t.SJ_SWJG_DM) 已发起省份数量
FROM
  FX_FPRW_TSJLB t 
WHERE t.YXBZ = 'Y'
  AND EXISTS(SELECT 1 FROM FX_QMFAMX_GX t1 WHERE t1.FXFAXH = t.FXFAXH AND t1.YXBZ = 'Y' AND t1.FXMXDM = 'MX144010000000504149');"""
qg_sql23="""SELECT
  t4.TJQJ 统计区间,
  COUNT(DISTINCT t4.SJ_SWJG_DM) 省份数量 
 FROM (
      SELECT
   t2.SJ_SWJG_DM,
   (
     CASE
       WHEN t3.WCXH IS NOT NULL THEN '已完成人工复评'
       WHEN t3.WCXH IS NULL AND t2.DQQJ <= 10 THEN '10天内未完成'
       WHEN t3.WCXH IS NULL AND t2.DQQJ > 10 AND t2.DQQJ <= 20 THEN '10-20天未完成'
       WHEN t3.WCXH IS NULL AND t2.DQQJ > 20 AND t2.DQQJ <= 30 THEN '20-30天未完成'
       WHEN t3.WCXH IS NULL AND t2.DQQJ > 30 THEN '30天以上未完成'
     END
   ) TJQJ,
   t2.FXFAXH
 FROM 
 (SELECT
   t.SJ_SWJG_DM, t.FPRWXH, t.FXFAXH, TIMESTAMPDIFF(DAY, MIN(t.lrrq), CONCAT(DATE(NOW()),' 16:00:00')) DQQJ
 FROM
   FX_FPRW_TSJLB t 
 WHERE t.YXBZ = 'Y'
   AND EXISTS(SELECT 1 FROM FX_QMFAMX_GX t1 WHERE t1.FXFAXH = t.FXFAXH AND t1.YXBZ = 'Y' AND t1.FXMXDM = 'MX000000000000000106')    
   GROUP BY t.SJ_SWJG_DM, t.FPRWXH, t.FXFAXH
 ) t2
 LEFT JOIN FX_RGFP_WCB t3 ON t3.FXFAXH = t2.FXFAXH AND t3.FPRWXH = t2.FPRWXH
 ) t4
 GROUP BY t4.TJQJ; """
qg_sql24="""SELECT
  t4.TJQJ 统计区间,
  COUNT(DISTINCT t4.SJ_SWJG_DM) 省份数量
 FROM (
      SELECT
   t2.SJ_SWJG_DM,
   (
     CASE
       WHEN t3.WCXH IS NOT NULL THEN '已完成人工复评'
       WHEN t3.WCXH IS NULL AND t2.DQQJ <= 10 THEN '10天内未完成'
       WHEN t3.WCXH IS NULL AND t2.DQQJ > 10 AND t2.DQQJ <= 20 THEN '10-20天未完成'
       WHEN t3.WCXH IS NULL AND t2.DQQJ > 20 AND t2.DQQJ <= 30 THEN '20-30天未完成'
       WHEN t3.WCXH IS NULL AND t2.DQQJ > 30 THEN '30天以上未完成'
     END
   ) TJQJ,
   t2.FXFAXH
 FROM 
 (SELECT
   t.SJ_SWJG_DM, t.FPRWXH, t.FXFAXH, TIMESTAMPDIFF(DAY, MIN(t.lrrq), CONCAT(DATE(NOW()),' 16:00:00')) DQQJ
 FROM
   FX_FPRW_TSJLB t 
 WHERE t.YXBZ = 'Y'
   AND EXISTS(SELECT 1 FROM FX_QMFAMX_GX t1 WHERE t1.FXFAXH = t.FXFAXH AND t1.YXBZ = 'Y' AND t1.FXMXDM = 'MX144010000000504149')    
   GROUP BY t.SJ_SWJG_DM, t.FPRWXH, t.FXFAXH
 ) t2
 LEFT JOIN FX_RGFP_WCB t3 ON t3.FXFAXH = t2.FXFAXH AND t3.FPRWXH = t2.FPRWXH
 ) t4 
GROUP BY t4.TJQJ;"""